version: '3.9'

services:
  db:
    build:
      context: ./db
    image: inventory-db
    environment:
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventorypass
      - POSTGRES_DB=inventorydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    image: inventory-backend
    environment:
    - DATABASE_URL=postgresql+psycopg2://inventory:inventorypass@db:5432/inventorydb
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    image: inventory-frontend
    networks:
      - app-net
    depends_on:
      - backend

  proxy:
    build:
      context: ./proxy
    image: inventory-proxy
    ports:
      - "80:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
    networks:
      - app-net
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
  frontend-dist:

networks:
  app-net:
    driver: overlay
